name: Compile LaTeX to PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: dante-ev/latex-action@v2
        with:
          latex-distribution: texlive-full

      - name: Compile LaTeX
        run: |
          cd "ECON 21020 Econometrics"
          latexmk -pdf -shell-escape -interaction=nonstopmode "20210 Notes.tex"

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: "ECON 21020 Econometrics/20210 Notes.pdf"
